Algoritmo "exercicio_64"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Mateus de Paula Ferreira
// Descrição   : Contagem com para
// Autor(a)    : Daniel Solano
// Data atual  : 28/10/2024
Var
// Seção de Declarações das variáveis 
n : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para n de 0 ate 40 passo 5 faca
escreva(n)
fimpara

Fimalgoritmo