Algoritmo "exercicio_67"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Mateus de Paula Ferreira
// Descrição   : Contagem até 0
// Autor(a)    : Daniel Solano
// Data atual  : 28/10/2024
Var
// Seção de Declarações das variáveis 
n : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o número: ")
leia(n)
para n de 0 ate n faca
escreva(n, ",")
fimpara
escreva(" FIM!")

Fimalgoritmo