Algoritmo "exercicio_71"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Mateus de Paula Ferreira
// Descrição   : Valor com vetores
// Autor(a)    : Daniel Solano
// Data atual  : 23/10/2024
Var
// Seção de Declarações das variáveis 
numero : vetor [0..7] de inteiro
i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para i de 0 ate 7 faca
numero[i] <- 999
fimpara

Fimalgoritmo